version: '3.1'

services:   
    mongo:
      image: mongo:latest
      ports: 
        - '27017:27017'
    node:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
          - '8080:8080'
          - '3000:3000'
      volumes: 
        - .:/app/pogo-coding-challenge
      depends_on:
        - mongo
